import type { AdminUser } from "./types";

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: "u-001",
    displayName: "Bao Nguyen",
    email: "bao.nguyen@ralion.com",
    systemRole: "ADMIN",
    status: "ACTIVE",
    projectCount: 1,
    createdAt: "2026-01-02",
    createdAtLabel: "02 thg 01, 2026",
    createdBy: "Khởi tạo hệ thống",
  },
  {
    id: "u-002",
    displayName: "Linh Tran",
    email: "linh.tran@ralion.com",
    systemRole: "HR",
    status: "ACTIVE",
    projectCount: 2,
    createdAt: "2026-01-05",
    createdAtLabel: "05 thg 01, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-003",
    displayName: "Minh Le",
    email: "minh.le@ralion.com",
    systemRole: "HR",
    status: "ACTIVE",
    projectCount: 3,
    createdAt: "2026-02-14",
    createdAtLabel: "14 thg 02, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-004",
    displayName: "Alex Nguyen",
    email: "alex.nguyen@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 4,
    createdAt: "2026-06-20",
    createdAtLabel: "20 thg 06, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-005",
    displayName: "Nguyen Minh Anh",
    email: "minh.anh@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 1,
    createdAt: "2026-08-04",
    createdAtLabel: "04 thg 08, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-006",
    displayName: "Le Hoang Nam",
    email: "nam.le@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 1,
    createdAt: "2026-07-27",
    createdAtLabel: "27 thg 07, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-007",
    displayName: "Pham Thu Ha",
    email: "ha.pham@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 1,
    createdAt: "2026-07-31",
    createdAtLabel: "31 thg 07, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-008",
    displayName: "Vu Thi Lan",
    email: "lan.vu@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 1,
    createdAt: "2026-08-07",
    createdAtLabel: "07 thg 08, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-009",
    displayName: "Tran Minh Khoa",
    email: "khoa.tran@ralion.com",
    systemRole: null,
    status: "INACTIVE",
    projectCount: 1,
    createdAt: "2026-07-21",
    createdAtLabel: "21 thg 07, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-010",
    displayName: "Do Quang Huy",
    email: "huy.do@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 1,
    createdAt: "2026-08-09",
    createdAtLabel: "09 thg 08, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-011",
    displayName: "Dang Hai Yen",
    email: "yen.dang@ralion.com",
    systemRole: null,
    status: "INACTIVE",
    projectCount: 0,
    createdAt: "2026-03-12",
    createdAtLabel: "12 thg 03, 2026",
    createdBy: "Bao Nguyen",
  },
  {
    id: "u-012",
    displayName: "Ngo Thi Cam",
    email: "cam.ngo@ralion.com",
    systemRole: null,
    status: "ACTIVE",
    projectCount: 0,
    createdAt: "2026-08-11",
    createdAtLabel: "11 thg 08, 2026",
    createdBy: "Bao Nguyen",
  },
];
