"""fix check constraint names and add deferred circular fk

Revision ID: 092eacb97740
Revises: 9fbecdaefe53
Create Date: 2026-08-11 00:55:53.565128

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '092eacb97740'
down_revision: str | Sequence[str] | None = '9fbecdaefe53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_blockers_ck_blockers_resolved_requires_resolved_at'), 'blockers', type_='check')
    op.create_check_constraint(op.f('ck_blockers_resolved_requires_resolved_at'), 'blockers', "status != 'RESOLVED' OR resolved_at IS NOT NULL")
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_scope_project_id'), 'knowledge_documents', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_documents_scope_project_id'), 'knowledge_documents', "(scope = 'PROJECT' AND project_id IS NOT NULL) OR (scope = 'ORGANIZATION' AND project_id IS NULL)")
    op.create_foreign_key('fk_projects_primary_pm_membership_id', 'projects', 'project_memberships', ['primary_pm_membership_id'], ['membership_id'], use_alter=True)
    op.drop_constraint(op.f('ck_support_departments_ck_support_departments_resolutio_a1c4'), 'support_departments', type_='check')
    op.drop_constraint(op.f('ck_support_departments_ck_support_departments_response__56a9'), 'support_departments', type_='check')
    op.create_check_constraint(op.f('ck_support_departments_resolution_sla_positive'), 'support_departments', 'resolution_sla_minutes > 0')
    op.create_check_constraint(op.f('ck_support_departments_response_sla_positive'), 'support_departments', 'response_sla_minutes > 0')
    op.drop_constraint(op.f('ck_support_requests_ck_support_requests_resolved_requir_5f99'), 'support_requests', type_='check')
    op.create_check_constraint(op.f('ck_support_requests_resolved_requires_resolved_at'), 'support_requests', "status NOT IN ('RESOLVED', 'CLOSED') OR resolved_at IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_support_requests_resolved_requires_resolved_at'), 'support_requests', type_='check')
    op.create_check_constraint(op.f('ck_support_requests_ck_support_requests_resolved_requir_5f99'), 'support_requests', "(status <> ALL (ARRAY['RESOLVED'::ticket_status, 'CLOSED'::ticket_status])) OR resolved_at IS NOT NULL")
    op.drop_constraint(op.f('ck_support_departments_response_sla_positive'), 'support_departments', type_='check')
    op.drop_constraint(op.f('ck_support_departments_resolution_sla_positive'), 'support_departments', type_='check')
    op.create_check_constraint(op.f('ck_support_departments_ck_support_departments_response__56a9'), 'support_departments', 'response_sla_minutes > 0')
    op.create_check_constraint(op.f('ck_support_departments_ck_support_departments_resolutio_a1c4'), 'support_departments', 'resolution_sla_minutes > 0')
    op.drop_constraint('fk_projects_primary_pm_membership_id', 'projects', type_='foreignkey')
    op.drop_constraint(op.f('ck_knowledge_documents_scope_project_id'), 'knowledge_documents', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_scope_project_id'), 'knowledge_documents', "scope = 'PROJECT'::document_scope AND project_id IS NOT NULL OR scope = 'ORGANIZATION'::document_scope AND project_id IS NULL")
    op.drop_constraint(op.f('ck_blockers_resolved_requires_resolved_at'), 'blockers', type_='check')
    op.create_check_constraint(op.f('ck_blockers_ck_blockers_resolved_requires_resolved_at'), 'blockers', "status <> 'RESOLVED'::blocker_status OR resolved_at IS NOT NULL")
    # ### end Alembic commands ###
