"""add template constraints one per project and one global

Revision ID: 87d27e78a497
Revises: b3c4d5e6f7a8
Create Date: 2026-08-12 16:44:45.373071

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87d27e78a497'
down_revision: str | Sequence[str] | None = 'b3c4d5e6f7a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_onboarding_templates_one_approved_per_project'), table_name='onboarding_templates', postgresql_where="((status = 'APPROVED'::template_status) AND (scope = 'PROJECT'::template_scope))")
    op.create_index('uq_onboarding_templates_one_global', 'onboarding_templates', ['scope'], unique=True, postgresql_where=sa.text("scope = 'GLOBAL'"))
    op.create_unique_constraint('uq_onboarding_templates_one_per_project', 'onboarding_templates', ['project_id'])
    op.create_index('uq_template_versions_one_approved_per_template', 'template_versions', ['template_id'], unique=True, postgresql_where=sa.text("status = 'APPROVED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_template_versions_one_approved_per_template', table_name='template_versions', postgresql_where=sa.text("status = 'APPROVED'"))
    op.drop_constraint('uq_onboarding_templates_one_per_project', 'onboarding_templates', type_='unique')
    op.drop_index('uq_onboarding_templates_one_global', table_name='onboarding_templates', postgresql_where=sa.text("scope = 'GLOBAL'"))
    op.create_index(op.f('uq_onboarding_templates_one_approved_per_project'), 'onboarding_templates', ['project_id'], unique=True, postgresql_where="((status = 'APPROVED'::template_status) AND (scope = 'PROJECT'::template_scope))")
    # ### end Alembic commands ###
