"""add remaining 20 entities

Revision ID: 9fbecdaefe53
Revises: 2fb68a7d5469
Create Date: 2026-08-11 00:45:17.278742

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9fbecdaefe53'
down_revision: str | Sequence[str] | None = '2fb68a7d5469'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('support_type', sa.Enum('HR', 'IT', 'SECURITY', 'PROJECT_OWNER', name='support_type'), nullable=False),
    sa.Column('response_sla_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_sla_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('resolution_sla_minutes > 0', name=op.f('ck_support_departments_ck_support_departments_resolution_sla_positive')),
    sa.CheckConstraint('response_sla_minutes > 0', name=op.f('ck_support_departments_ck_support_departments_response_sla_positive')),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_support_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_support_departments_name'))
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_id_created_at', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id_created_at', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEADLINE', 'BLOCKED', 'TICKET_UPDATE', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_read_at_created_at', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_pm_membership_id', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='project_status'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.user_id'], name=op.f('fk_projects_created_by_admin_id_users')),
    sa.ForeignKeyConstraint(['primary_pm_membership_id'], ['project_memberships.membership_id'], name='fk_projects_primary_pm_membership_id', use_alter=True),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects')),
    sa.UniqueConstraint('key', name=op.f('uq_projects_key'))
    )
    op.create_table('knowledge_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('ORGANIZATION', 'PROJECT', name='document_scope'), nullable=False),
    sa.Column('category', sa.Enum('POLICY', 'OVERVIEW', 'ARCHITECTURE', 'SETUP', 'ACCESS_SECURITY', 'CODEBASE_GUIDE', 'CONVENTION', 'WORKFLOW', 'REFERENCE_PR', name='document_category'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'PROJECT' AND project_id IS NOT NULL) OR (scope = 'ORGANIZATION' AND project_id IS NULL)", name=op.f('ck_knowledge_documents_ck_knowledge_documents_scope_project_id')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], name=op.f('fk_knowledge_documents_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_knowledge_documents_project_id_projects')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_knowledge_documents'))
    )
    op.create_table('onboarding_templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_template_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('GLOBAL', 'PROJECT', name='template_scope'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'NEEDS_REVIEW', 'ARCHIVED', name='template_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_onboarding_templates_project_id_projects')),
    sa.ForeignKeyConstraint(['source_template_id'], ['onboarding_templates.template_id'], name=op.f('fk_onboarding_templates_source_template_id_onboarding_templates')),
    sa.PrimaryKeyConstraint('template_id', name=op.f('pk_onboarding_templates'))
    )
    op.create_index('uq_onboarding_templates_one_approved_per_project', 'onboarding_templates', ['project_id'], unique=True, postgresql_where=sa.text("status = 'APPROVED' AND scope = 'PROJECT'"))
    op.create_table('project_memberships',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_role', sa.Enum('PM', 'ENGINEER', name='project_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='membership_status'), nullable=False),
    sa.Column('assigned_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_admin_id'], ['users.user_id'], name=op.f('fk_project_memberships_assigned_by_admin_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_memberships_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_project_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('membership_id', name=op.f('pk_project_memberships')),
    sa.UniqueConstraint('user_id', 'project_id', name=op.f('uq_project_memberships_user_id'))
    )
    op.create_table('document_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'ACTIVE', 'FAILED', 'ARCHIVED', name='version_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.document_id'], name=op.f('fk_document_versions_document_id_knowledge_documents')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_no', name=op.f('uq_document_versions_document_id'))
    )
    op.create_index('uq_document_versions_one_active_per_document', 'document_versions', ['document_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('template_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='template_version_status'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.user_id'], name=op.f('fk_template_versions_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['template_id'], ['onboarding_templates.template_id'], name=op.f('fk_template_versions_template_id_onboarding_templates')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_template_versions')),
    sa.UniqueConstraint('template_id', 'version_no', name=op.f('uq_template_versions_template_id'))
    )
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], name=op.f('fk_document_chunks_version_id_document_versions')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('vector_id', name=op.f('uq_document_chunks_vector_id')),
    sa.UniqueConstraint('version_id', 'chunk_index', name=op.f('uq_document_chunks_version_id'))
    )
    op.create_table('onboarding_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('template_version_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ACTIVE', 'PROJECT_READY', 'ONBOARDING_CLOSED', name='plan_status'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.user_id'], name=op.f('fk_onboarding_plans_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['membership_id'], ['project_memberships.membership_id'], name=op.f('fk_onboarding_plans_membership_id_project_memberships')),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.version_id'], name=op.f('fk_onboarding_plans_template_version_id_template_versions')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_onboarding_plans'))
    )
    op.create_index('uq_onboarding_plans_one_open_per_membership', 'onboarding_plans', ['membership_id'], unique=True, postgresql_where=sa.text("status != 'ONBOARDING_CLOSED'"))
    op.create_table('template_tasks',
    sa.Column('template_task_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ORIENTATION', 'ACCESS', 'SETUP', 'CODEBASE', 'CONVENTION', 'FIRST_TASK', 'FIRST_PR', name='task_category'), nullable=False),
    sa.Column('title_pattern', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('instruction_template', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['template_versions.version_id'], name=op.f('fk_template_tasks_version_id_template_versions')),
    sa.PrimaryKeyConstraint('template_task_id', name=op.f('pk_template_tasks')),
    sa.UniqueConstraint('version_id', 'display_order', name=op.f('uq_template_tasks_version_id'))
    )
    op.create_table('plan_tasks',
    sa.Column('plan_task_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('template_task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='task_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['onboarding_plans.plan_id'], name=op.f('fk_plan_tasks_plan_id_onboarding_plans')),
    sa.ForeignKeyConstraint(['template_task_id'], ['template_tasks.template_task_id'], name=op.f('fk_plan_tasks_template_task_id_template_tasks')),
    sa.PrimaryKeyConstraint('plan_task_id', name=op.f('pk_plan_tasks')),
    sa.UniqueConstraint('plan_id', 'display_order', name=op.f('uq_plan_tasks_plan_id'))
    )
    op.create_table('task_dependencies',
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('predecessor_task_id', sa.Integer(), nullable=False),
    sa.Column('successor_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['template_tasks.template_task_id'], name=op.f('fk_task_dependencies_predecessor_task_id_template_tasks')),
    sa.ForeignKeyConstraint(['successor_task_id'], ['template_tasks.template_task_id'], name=op.f('fk_task_dependencies_successor_task_id_template_tasks')),
    sa.PrimaryKeyConstraint('dependency_id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('predecessor_task_id', 'successor_task_id', name=op.f('uq_task_dependencies_predecessor_task_id'))
    )
    op.create_table('blockers',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('plan_task_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_membership_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ACCESS', 'SETUP', 'DOCUMENT', 'TECHNICAL', 'OTHER', name='blocker_category'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ROUTED', 'RESOLVED', name='blocker_status'), nullable=False),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status != 'RESOLVED' OR resolved_at IS NOT NULL", name=op.f('ck_blockers_ck_blockers_resolved_requires_resolved_at')),
    sa.ForeignKeyConstraint(['plan_task_id'], ['plan_tasks.plan_task_id'], name=op.f('fk_blockers_plan_task_id_plan_tasks')),
    sa.ForeignKeyConstraint(['reported_by_membership_id'], ['project_memberships.membership_id'], name=op.f('fk_blockers_reported_by_membership_id_project_memberships')),
    sa.PrimaryKeyConstraint('blocker_id', name=op.f('pk_blockers'))
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('context_plan_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_plan_task_id'], ['plan_tasks.plan_task_id'], name=op.f('fk_chat_sessions_context_plan_task_id_plan_tasks')),
    sa.ForeignKeyConstraint(['membership_id'], ['project_memberships.membership_id'], name=op.f('fk_chat_sessions_membership_id_project_memberships')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_chat_sessions'))
    )
    op.create_table('plan_task_sources',
    sa.Column('task_source_id', sa.Integer(), nullable=False),
    sa.Column('plan_task_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('citation_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_task_id'], ['plan_tasks.plan_task_id'], name=op.f('fk_plan_task_sources_plan_task_id_plan_tasks')),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], name=op.f('fk_plan_task_sources_version_id_document_versions')),
    sa.PrimaryKeyConstraint('task_source_id', name=op.f('pk_plan_task_sources')),
    sa.UniqueConstraint('plan_task_id', 'version_id', name=op.f('uq_plan_task_sources_plan_task_id'))
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name=op.f('fk_chat_messages_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_chat_messages'))
    )
    op.create_table('support_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticket_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status NOT IN ('RESOLVED', 'CLOSED') OR resolved_at IS NOT NULL", name=op.f('ck_support_requests_ck_support_requests_resolved_requires_resolved_at')),
    sa.ForeignKeyConstraint(['blocker_id'], ['blockers.blocker_id'], name=op.f('fk_support_requests_blocker_id_blockers')),
    sa.ForeignKeyConstraint(['department_id'], ['support_departments.department_id'], name=op.f('fk_support_requests_department_id_support_departments')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_support_requests'))
    )
    op.create_table('citations',
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], name=op.f('fk_citations_chunk_id_document_chunks')),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], name=op.f('fk_citations_message_id_chat_messages')),
    sa.PrimaryKeyConstraint('citation_id', name=op.f('pk_citations')),
    sa.UniqueConstraint('message_id', 'chunk_id', name=op.f('uq_citations_message_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    op.drop_table('support_requests')
    op.drop_table('chat_messages')
    op.drop_table('plan_task_sources')
    op.drop_table('chat_sessions')
    op.drop_table('blockers')
    op.drop_table('task_dependencies')
    op.drop_table('plan_tasks')
    op.drop_table('template_tasks')
    op.drop_index('uq_onboarding_plans_one_open_per_membership', table_name='onboarding_plans', postgresql_where=sa.text("status != 'ONBOARDING_CLOSED'"))
    op.drop_table('onboarding_plans')
    op.drop_table('document_chunks')
    op.drop_table('template_versions')
    op.drop_index('uq_document_versions_one_active_per_document', table_name='document_versions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('document_versions')
    op.drop_table('project_memberships')
    op.drop_index('uq_onboarding_templates_one_approved_per_project', table_name='onboarding_templates', postgresql_where=sa.text("status = 'APPROVED' AND scope = 'PROJECT'"))
    op.drop_table('onboarding_templates')
    op.drop_table('knowledge_documents')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_id_read_at_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_entity_type_entity_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('support_departments')
    # ### end Alembic commands ###
