import { stripLocale } from "@/i18n/routing";

export const SHALLOW_NAVIGATION_EVENT = "ralion:shallow-navigation";

function resolveSamePageUrl(href: string) {
  if (typeof window === "undefined") return null;

  const target = new URL(href, window.location.href);
  if (target.origin !== window.location.origin) return null;
  if (stripLocale(target.pathname) !== stripLocale(window.location.pathname)) return null;

  // Href generated by next-intl uses the logical path (`/user`) while the browser is
  // actually on a localized path (`/vi/user`). Keep the current pathname and only
  // change search/hash so the update never crosses a Next.js route boundary.
  return `${window.location.pathname}${target.search}${target.hash}`;
}

export function canShallowNavigate(href: string) {
  return resolveSamePageUrl(href) !== null;
}

/**
 * Update query state on the current page without asking the App Router for a new
 * React Server Component payload. Next.js integrates native History API entries
 * with useSearchParams, so bookmark/deep-link and Back/Forward behavior are kept.
 */
export function shallowNavigate(href: string, replace = false) {
  const nextUrl = resolveSamePageUrl(href);
  if (nextUrl === null) return false;
  if (`${window.location.pathname}${window.location.search}${window.location.hash}` === nextUrl) {
    return true;
  }

  if (replace) window.history.replaceState(null, "", nextUrl);
  else window.history.pushState(null, "", nextUrl);
  window.dispatchEvent(new Event(SHALLOW_NAVIGATION_EVENT));
  return true;
}
